name: 'Setup Node.js & Install Dependencies'
# inputs:
  # NODE_AUTH_TOKEN:
  #   description: 'Token that has rights to install traveloka dependencies'
  #   required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        always-auth: true
        registry-url: https://registry.npmjs.org
        scope: '@traveloka:registry'
    - name: Get Node version
      id: node-version
      shell: bash
      run: echo "version=$(cat .nvmrc | tr -d '\n')" >> $GITHUB_OUTPUT
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-node${{ steps.node-version.outputs.version }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      shell: bash
      run: yarn install --prefer-offline --frozen-lockfile
      # env:
      #   NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
