name: 'Update Version'
description: 'Update version numbers in Android and iOS project files based on branch name'

runs:
  using: 'composite'
  steps:
    - name: Create dummy file
      run: echo "dummy content 2" > dummy-2.txt
      shell: bash