name: "Delete Branch"
inputs:
  delete_branch:
    description: "Branch to delete"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Delete Branch
      uses: actions/github-script@v7
      with:
        script: |
          const branchToDelete = '${{ inputs.delete_branch }}';
          if (branchToDelete != 'test-only' && !branchToDelete.startsWith('test/')) {
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branchToDelete}`
            });
            console.log('Delete branch', branchToDelete);
          } else {
            core.setFailed('Refusing to delete protected branch: ' + branchToDelete);
          }
