name: 'Delete Branch'
inputs:
  delete_branch:
    description: "Branch to delete"
    required: true
    type: string
  GITHUB_TOKEN:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Delete Branch
      uses: actions/github-script@v7
      shell: bash
      env:
        DELETE_BRANCH: ${{ inputs.delete_branch }}
      with:
        script: |
          const { DELETE_BRANCH } = process.env;
          await github.rest.git.deleteRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `heads/${DELETE_BRANCH}`
          });
          console.log('Delete branch', DELETE_BRANCH);
