name: 'Delete Branch'
inputs:
  delete_branch:
    description: "Branch to delete"
    required: true
    type: string
  GITHUB_TOKEN:
    required: true
    type: string
  REPO_OWNER:
    required: true
    type: string
  REPO_NAME:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Override git config
      shell: bash
      run: git config --global url."https://${{ inputs.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
    - name: Delete Branch
      uses: actions/github-script@v7
      with:
        script: |
          const branchToDelete = '${{ inputs.delete_branch }}';
          await github.rest.git.deleteRef({
            owner: '${{ inputs.REPO_OWNER }}',
            repo: '${{ inputs.REPO_NAME }}',
            ref: `heads/${branchToDelete}`
          });
          console.log('Delete branch', branchToDelete);
