name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  create:
    uses: ./.github/workflows/force-push.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: "master"
      target_branch: "reset-shared-staging"

  update:
    environment: auto-reset
    needs: create
    uses: ./.github/workflows/force-push.yml
    with:
      base_branch: "reset-shared-staging"
      target_branch: "feat/shared-staging"