name: Scheduled Reset Shared Staging
env:
  RESET_BRANCH: 'chore/reset-shared-staging'
  SHARED_STAGING_BRANCH: 'chore/shared-staging'
on:
  schedule:
    - cron: '0 3 1-7 * 2' # At 10.00 AM (GMT+7) on every first Tuesday of the month
  workflow_dispatch:

jobs:
  push_shared_staging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Force push to shared staging branch
        uses: ./.github/actions/force-push
        with:
          base_branch: $RESET_BRANCH
          target_branch: $SHARED_STAGING_BRANCH
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete_reset_branch:
    runs-on: ubuntu-latest
    needs: push_shared_staging
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Delete Branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchToDelete = '${{ process.env.RESET_BRANCH }}';
            if (branchToDelete != 'develop' && !branchToDelete.startsWith('test/')) {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchToDelete}`
              });
              console.log('Delete branch', branchToDelete);
            } else {
              core.setFailed('Refusing to delete branch: ' + branchToDelete);
            }


  # post_completed:
  #   runs-on: ubuntu-latest
  #   needs: push_shared_staging
  #   steps:
  #     - name: Post to a Lark channel
  #       uses: traveloka/act-devops-playground/.github/actions/post-to-lark@main
  #       with:
  #         app_id: ${{ secrets.ASTUTI_LARK_APP_ID }}
  #         app_secret: ${{ secrets.ASTUTI_LARK_APP_SECRET }}
  #         channel_name: "adn-testing"
  #         content: "{\"en_us\":{\"title\":\"Shared Staging Reset Completed\",\"content\":[[{\"tag\":\"text\",\"text\":\"The shared staging branch \"},{\"tag\":\"text\",\"text\":\"${{ inputs.target_branch }} \",\"style\":[\"bold\"]},{\"tag\":\"text\",\"text\":\"has been updated with the latest changes from \"},{\"tag\":\"text\",\"text\":\"${{ inputs.base_branch }}\",\"style\":[\"bold\"]},{\"tag\":\"emotion\",\"emoji_type\":\"CheckMark\"}],[{\"tag\":\"text\",\"text\":\"\\nYou can now continue development and testing on \"},{\"tag\":\"text\",\"text\":\"${{ inputs.target_branch }}.\",\"style\":[\"bold\"]}]]}}"
  #         content_type: "post"
