name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset*

jobs:
  create_reset_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create temporary reset branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "master"
          target_branch: "reset-shared-staging"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  reset_shared_staging:
    runs-on: ubuntu-latest
    needs: create_reset_branch
    environment: auto-reset
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Force push to shared staging branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "reset-shared-staging"
          target_branch: "feat/shared-staging"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete reset branch
        uses: ./.github/actions/delete-branch
        with:
          delete_branch: "reset-shared-staging"
  