name: Scheduled Reset Shared Staging
env:
  RESET_BRANCH: "reset-shared-staging"
  SHARED_STAGING_BRANCH: "feat/shared-staging"
on:
  push:
    branches:
      - chore/test-env

jobs:
  create_reset_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create temporary reset branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "master"
          target_branch: $RESET_BRANCH
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TODO: post to lark
  # needs: create_reset_branch

  reset_shared_staging:
    needs: create_reset_branch
    uses: ./.github/workflows/reset-shared-staging.yml
    permissions:
      contents: write
    with:
      base_branch: $RESET_BRANCH
      target_branch: $SHARED_STAGING_BRANCH
