name: Scheduled Reset Shared Staging
on:
  schedule:
    - cron: '0 3 1-7 * 1' # At 10.00 AM (GMT+7) on every first Monday of the month
  workflow_dispatch:

env:
  RESET_BRANCH: 'reset-shared-staging'
  SHARED_STAGING_BRANCH: 'feat/shared-staging'

jobs:
  create_reset_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create temporary reset branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "master"
          target_branch: ${{ env.RESET_BRANCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # TODO: post to lark
  # needs: create_reset_branch

  reset_shared_staging:
    needs: create_reset_branch
    uses: ./.github/workflows/reset-shared-staging.yml
    permissions:
      contents: write
    with:
      base_branch: ${{ env.RESET_BRANCH }}
      target_branch: ${{ env.SHARED_STAGING_BRANCH }}
  