name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  create_reset_branch:
    uses: ./.github/workflows/reset-shared-staging.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: "master"
      target_branch: "reset-shared-staging"
      delete_base_branch: false

  reset_shared_staging:
    uses: ./.github/workflows/reset-shared-staging.yml
    needs: create_reset_branch
    environment: auto-reset
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: "reset-shared-staging"
      target_branch: "feat/shared-staging"
      delete_base_branch: true
  