name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset
  # workflow_dispatch:
  #   inputs:
  #     reset_branch:
  #       description: "Temporary Reset Branch"
  #       required: true
  #       type: string
  #       default: "reset-shared-staging"
  #     shared_staging_branch:
  #       description: "Target Shared Staging Branch"
  #       required: true
  #       type: string
  #       default: "feat/shared-staging"

jobs:
  upsert:
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: ./.github/workflows/force-push.yml
        with:
          base_branch: "master"
          target_branch: "reset-shared-staging"
