name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  create:
    uses: ./.github/workflows/force-push.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: "master"
      target_branch: "reset-shared-staging"

  approval:
    runs-on: ubuntu-latest
    needs: create
    environment: auto-reset
    steps:
      - name: Awaiting approval
        run: echo "Waiting for approval to proceed with resetting shared staging branch."

  shared_staging:
    runs-on: ubuntu-latest
    needs: approval
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: upsert
        uses: ./.github/workflows/force-push.yml
        with:
          base_branch: "reset-shared-staging"
          target_branch: "feat/shared-staging"
