name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  upsert:
    runs-on: ubuntu-latest
    environment: auto-reset
    steps:
      - name: testing steps
        secrets: inherit
        permissions:
          contents: write
          id-token: write
        run: echo "This is a test step"
