name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  test_echo:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/test-echo
        with:
          delete_branch: 'echo test only'
