name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset*

jobs:
  create_reset_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create or Force Push reset branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "master"
          target_branch: "reset-shared-staging"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # waiting_per_approval:
  #   runs-on: ubuntu-latest
  #   needs: create_reset_branch
  #   environment: auto-reset
  #   steps:
  #     - run: echo "Approved."

  # reset_shared_staging:
  #   uses: ./.github/workflows/reset-shared-staging.yml
  #   needs: waiting_per_approval
  #   secrets: inherit
  #   permissions:
  #     contents: write
  #     id-token: write
  #   with:
  #     base_branch: "reset-shared-staging"
  #     target_branch: "feat/shared-staging"
  #     delete_base_branch: false
  
  # delete_reset_branch:
  #   runs-on: ubuntu-latest
  #   needs: reset_shared_staging
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Delete reset branch
  #       uses: ./.github/actions/delete-branch
  #       with:
  #         delete_branch: "reset-shared-staging"
  