name: Auto Reset
run-name: Reset test branch
on:
  push:
    branches:
      - feat/test-auto-reset

jobs:
  upsert:
    runs-on: ubuntu-latest
    steps:
      - name: testing steps
        run: echo "This is a test step"
