name: Auto Reset
run-name: Reset test branch
on:
  workflow_dispatch:
    inputs:
      reset_branch:
        description: 'Temporary Reset Branch'
        required: true
        type: string
        default: 'reset-shared-staging'
      shared_staging_branch:
        description: 'Target Shared Staging Branch'
        required: true
        type: string
        default: 'feat/shared-staging'

jobs:
  upsert:
    uses: ./.github/workflows/force-push.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: "master"
      target_branch: ${{ inputs.reset_branch }}
      delete_branch: false

  force:
    needs: upsert
    uses: ./.github/workflows/force-push.yml
    secrets: inherit
    permissions:
      contents: write
      id-token: write
    with:
      base_branch: ${{ inputs.reset_branch }}
      target_branch: ${{ inputs.shared_staging_branch }}
      delete_branch: true
