name: cache-release

on:
  workflow_run:
    workflows: [Test Echo - Cache]
    types: [completed]

jobs: 
  cache-release:
    name: Cache Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - run: yarn install --prefer-offline --frozen-lockfile