name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  push-commit:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
      branch: ${{ steps.create-branch.outputs.branch }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Create new branch
        id: create-branch
        run: |
          BRANCH_NAME="version-bump-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME master
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - uses: fregante/setup-git-user@v2
      # - name: Override git config
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: .nvmrc
          cache: "yarn"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      - name: Update version & changelog
        id: publish
        run: |
          OUTPUT=$(yarn run:publish patch)
          echo "$OUTPUT"
          VERSION=$(echo "$OUTPUT" | grep "version=" | cut -d'=' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      # - name: Update readme
      #   run: |
      #     # Or replace specific content
      #     sed -i 's/🚀 This is an awesome \[Next.js\]/🚀 This is a super awesome [Next.js]/' README.md

      - name: Create and push new branch with commit
        run: |
          git add .
          git commit -m "chore: bump version to ${{ steps.publish.outputs.version }}"
          git push origin ${{ steps.create-branch.outputs.branch }}
  create-pull-request:
    name: Create Pull Request
    needs: push-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Creating pull request...');
            try {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: '${{ needs.push-commit.outputs.branch }}',
                base: 'master',
                title: 'chore: bump version to ${{ needs.push-commit.outputs.version }}',
                body: 'Automated version bump and changelog update',
                draft: true,
              });
            } catch (error) {
              console.error(`Error creating pull request: ${error.message}`);
              process.exit(1);
            }
