name: Create Pull Request

on:
  push:
    branches:
      - action-pull-request

jobs:
  push-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create and push new branch with commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Create a new branch
          git fetch origin action-pull-request
          git checkout action-pull-request

          # make changes to trigger the pull request process
          echo "Triggering pull request process by making a dummy change." > dummy.txt

          # Stage, commit, and push the changes
          git commit -m "Trigger pull request process"
          git push origin action-pull-request
  create-pull-request:
    name: Create Pull Request
    needs: push-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Creating pull request...');
            try {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: 'action-pull-request',
                base: 'master',
                title: 'Automated Pull Request',
              });
            } catch (error) {
              console.error(`Error creating pull request: ${error.message}`);
              process.exit(1);
            }
