name: Create Lark Ticket

on:
  push:
    branches:
      - feat/webhook

jobs:
  # create-lark-ticket:
  #   name: Create Lark Ticket
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send POST request with JSON
  #       run: |
  #         curl -X POST "https://traveloka.sg.larksuite.com/base/automation/webhook/event/Akgma6ZQDwhakQh5sG9lCqQbgNg" \
  #         -H "Content-Type: application/json" \
  #         -d '{"prTitle": "chore: this is testing only"}'

  # get-workflow-history:
  #   name: Get Workflow History
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Fetch
  #       run: |
  #         curl -L \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
  #         -H "X-GitHub-Api-Version: 2026-03-10" \
  #         https://api.github.com/repos/nisadn/test-github-pages/actions/runs

  create-jira-ticket:
    name: Create Jira Ticket
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request with JSON to Jira
        run: |
          curl -X POST -H 'Content-type: application/json' -H 'X-Automation-Webhook-Token: 25a2e953f06ff1204f6f88955d52153938ab8e90' \
          --data '{"issues":["TEST-1"]}' \
          https://api-private.atlassian.com/automation/webhooks/jira/a/7a5602d2-a791-4344-9822-807037202b17/019d951d-beae-7c83-9f24-4530d5d44a7d
