name: Delete Branch

on:
  workflow_call:
    inputs:
      delete_branch:
        description: "Branch to delete"
        required: true
        type: string

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    if: ${{ inputs.delete_branch != 'master' && !startsWith(inputs.delete_branch, 'test/') }}
    steps:
      - name: Override git config
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - name: Delete Branch
        uses: actions/github-script@v7
        env:
          DELETE_BRANCH: ${{ inputs.delete_branch }}
        with:
          script: |
            const { DELETE_BRANCH } = process.env;
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${DELETE_BRANCH}`
            });
            console.log('Delete branch', DELETE_BRANCH);
