name: Deploy Storybook

on:
  push:
    tags:
      - 'v*.*.*' # Matches semantic versioning tags like v1.0.0, v2.1.3, etc.
  workflow_call: 
    inputs: 
      checkout_tags:
        description: 'Tags to deploy'
        required: true
        default: 'master'
        type: string
  workflow_dispatch:
    inputs: 
      checkout_tags:
        description: 'Tags to deploy'
        required: true
        default: 'master'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #   with:
      #     fetch-tags: true

      # - name: Checkout specific tag
      #   uses: chachako/checkout-tags@v1
      #   with:
      #     base: nisadn/test-github-pages

      # - name: Verify checked-out tag
      #   run: |
      #     echo "Checked-out commit:"
      #     git log -1 --oneline
      #     echo "Checked-out tag:"
      #     git describe --tags --exact-match || echo "No tag found"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: .nvmrc
          cache: 'yarn'
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      
      - name: Build static storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: build-storybook -o storybook-static

      # Runs upload artifacts
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
  
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
