name: Deploy Storybook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        id: validate-branch
        run: |
          ALLOWED_BRANCHES=("refs/heads/master" "refs/heads/test-deploy")
          if [[ ! " ${ALLOWED_BRANCHES[@]} " =~ " ${GITHUB_REF} " ]]; then
            echo "Error: The branch '${GITHUB_REF}' is not allowed for deployment."
            exit 1
          fi
        env:
          GITHUB_REF: ${{ github.ref }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: .nvmrc
          cache: 'yarn'
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      
      - name: Build static storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: build-storybook -o storybook-static

      # Runs upload artifacts
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
  
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
