name: Deploy Storybook

on:
  push:
    branches:
      - test-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version: 21
          cache: 'yarn'
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command
      
      - name: Build static storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: build-storybook -o storybook-static

      # Runs upload artifacts
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static
  
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
