name: Deploy Storybook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feat/jsdoc

      - name: Get Latest Commit in Branch
        run: |
          echo "LATEST_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
      
      # Step 2: Generate a JSON file
      - name: Generate deployment info JSON
        run: |
          echo '```json
          {
            "source": "feat/jsdoc",
            "last_commit": "'$LATEST_COMMIT'"
          }
          ```' > ./stories/whoami.mdx

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: .nvmrc
          cache: 'yarn'
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile # will run `yarn install` command

      - name: Build static storybook
        uses: borales/actions-yarn@v4
        with:
          cmd: build-storybook -o docs

      - name: Make another html
        run: |
          mkdir -p docs/extra-folder
          echo "<!DOCTYPE html><html><body><h1>Extra HTML Page</h1></body></html>" > docs/extra-folder/index.html

      - name: Build jsdoc
        uses: borales/actions-yarn@v4
        with:
          cmd: docs --out docs/utils

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
