name: Publish Workflow

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Set to 'true' to force the workflow to fail"
        required: true
        default: "false"
        type: string
      package:
        type: choice
        description: Package name
        required: true
        options:
          - accomfe-ui
          - another-package

jobs:
  force-fail:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.run-publish-script.outputs.tags }}
    steps:
      - name: Check input and force failure if needed
        run: |
          echo "Checking input..."
          if [ "${{ github.event.inputs.force_fail }}" = "true" ]; then
            echo "Input is true. Forcing the workflow to fail."
            exit 1
          else
            echo "Input is false. Workflow will succeed."
          fi

      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Run Publish
        id: run-publish-script
        run: |
          echo "Running publish script for accomfe-ui"
          # Add your publish commands here
          OUTPUT=$(yarn run:publish)
          echo "tags=$OUTPUT" >> "$GITHUB_OUTPUT"
          echo "Publish script completed successfully."

  deploy:
    uses: ./.github/workflows/deploy-storybook.yml
    needs: force-fail
    with:
      checkout_tags: ${{ needs.force-fail.outputs.new_tag }}
    permissions:
      contents: read
      pages: write
      id-token: write