name: Publish Workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run publish steps
        run: echo "Publishing from master branch"

      - name: Trigger deploy workflow
        run: echo "Publish workflow completed successfully"

      - name: Trigger workflow on develop branch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: trigger-develop
