name: "[Testing] Request to Publish"

on:
  push:
    branches:
      - testing/push

jobs:
  create-pull-request:
    name: Create Pull Request to publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Changes
        uses: ./.github/actions/update-version
      - name: Another Changes
        if: github.event.created == true
        uses: ./.github/actions/update-version-dummy
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: '3250249'
          private-key: ${{ secrets.MOCCHI_BOT_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          title: "Automated PR"
          commit-message: "Update"
          branch: "publish-rc"
          base: ${{ github.ref_name }}
