name: Publish Workflow

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run publish steps
        run: echo "Publishing from master branch"

      - name: Trigger deploy workflow
        run: echo "Publish workflow completed successfully"

      - name: Trigger workflow on develop branch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: trigger-develop
