name: Publish Workflow

on:
  workflow_dispatch:
    inputs:
      force_fail:
        description: "Set to 'true' to force the workflow to fail"
        required: true
        default: "false"
        type: string
      package:
        type: choice
        description: Package name
        required: true
        options:
          - accomfe-ui
          - another-package

jobs:
  force-fail:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.run-publish-script.outputs.tags }}
    steps:
      - name: Check input and force failure if needed
        run: |
          echo "Checking input..."
          if [ "${{ github.event.inputs.force_fail }}" = "true" ]; then
            echo "Input is true. Forcing the workflow to fail."
            exit 1
          else
            echo "Input is false. Workflow will succeed."
          fi

  deploy:
    needs: force-fail
    permissions:
      contents: read
      pages: write
      id-token: write
    outputs:
      latest_tag: ${{ steps.get-latest-tag.outputs.latest_tag }}
    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "Fetching latest tag..."
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest_tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
          echo "Latest tag is: $LATEST_TAG"

      - name: "Deploying"
        uses: ./.github/workflows/deploy-storybook.yml
        with:
          checkout_tags: ${{ needs.force-fail.outputs.new_tag }}
