name: Reset Shared Staging

on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        description: "Temporary reset branch"
        required: true
      target_branch:
        type: string
        description: "Shared staging branch to reset"
        required: true

jobs:
  push_shared_staging:
    runs-on: ubuntu-latest
    environment: auto-reset
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Force push to shared staging branch
        uses: ./.github/actions/force-push
        with:
          base_branch: "${{ inputs.base_branch }}"
          target_branch: "${{ inputs.target_branch }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete_reset_branch:
    runs-on: ubuntu-latest
    needs: push_shared_staging
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Delete reset branch
        uses: ./.github/actions/delete-branch
        with:
          delete_branch: "${{ inputs.base_branch }}"

  # TODO: post to lark
  # needs: push_shared_staging
