name: Reset shared staging

on:
  workflow_call:

jobs:
  # reset_shared_staging:
  #   runs-on: ubuntu-latest
  #   environment: auto-reset
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.ref }}
  #     - name: Force push to shared staging branch
  #       uses: ./.github/actions/force-push
  #       with:
  #         base_branch: "reset-shared-staging"
  #         target_branch: "feat/shared-staging"
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  delete_reset_branch:
    runs-on: ubuntu-latest
    # needs: reset_shared_staging
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Delete reset branch
        uses: ./.github/actions/delete-branch
        with:
          delete_branch: "test/nothing"

