name: Create or Update Branch

on:
  workflow_call:
    inputs:
      base_branch:
        description: "Base branch to create the new branch from"
        required: true
        default: "develop"
        type: string
      target_branch:
        description: "Target branch to create or update"
        required: true
        type: string
    outputs:
      upsert_result:
        value: ${{ jobs.create_or_update_branch.outputs.upsert_result }}

jobs:
  create_or_update_branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upsert_result: ${{ steps.upsert_branch.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Override git config
        run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
      - name: Upsert branch
        id: upsert_branch
        run: |
          TARGET_BRANCH=${{ inputs.target_branch }}
          BASE_BRANCH=${{ inputs.base_branch }}
          git fetch origin $BASE_BRANCH
          git checkout $BASE_BRANCH

          echo "Creating new branch $TARGET_BRANCH."
          git checkout -b $TARGET_BRANCH
          git push origin $TARGET_BRANCH
          echo "result=Newly Created: $TARGET_BRANCH" >> "$GITHUB_OUTPUT"
